---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: <%= ENV["machine_port"] %>
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

provisioner:
  name: salt_solo
  is_file_root: True
  grains:
    vagrant: true
  pillars-from-files:
    kitchen.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - kitchen
  state_top:
    base:
      '*':
        - system
        - services
        - web

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
