---
driver:
  name: vagrant
  customize:
    memory: 1024
  synced_folders:
    - ["./test/certs", "/etc/letsencrypt/live"]

provisioner:
  name: salt_solo
  is_file_root: true
  state_top_from_file: true
  pillars-from-files:
    user.sls: test/pillars/user.sls
  pillars:
    top.sls:
      base:
        '*':
          - user

platforms:
  - name: debian-8.6
  - name: ubuntu-14.04

suites:
  - name: nothing

  - name: base
    provisioner:
      grains:
        roles:
          - server

  - name: webserver
    provisioner:
      pillars-from-files:
        everything.sls: test/pillars/webserver.sls
      pillars:
        top.sls:
          base:
            '*':
              - user
              - everything
      grains:
        roles:
          - server
          - webserver
