---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  is_file_root: True
  grains:
    vagrant: true
  pillars-from-files:
    kitchen.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - kitchen
  state_top:
    base:
      '*':
        - system
platforms:
  - name: debian-8.6
  - name: ubuntu-14.04

suites:
  - name: default
