---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  is_file_root: true
  state_top_from_file: true
  grains:
    vagrant: True
    ssl: False
  pillars-from-files:
    everything.sls: test/pillar.sls
  pillars:
    top.sls:
      base:
        '*':
          - everything

platforms:
  - name: debian-8.6
  - name: ubuntu-14.04
  - name: centos-7.3

suites:
  - name: default
