---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]
    - ["forwarded_port", {guest: 443, host: 8443}]
  synced_folders:
    - ["./test/certs", "/etc/letsencrypt/live"]

provisioner:
  name: salt_solo
  is_file_root: true
  state_top:
    base:
      '*':
        - locale
        - iptables
        - ssh
        - user
        - docker
        - nginx

  pillars-from-files:
    default.sls: test/pillars/default.sls

  pillars:
    top.sls:
      base:
        '*':
          - default

  grains:
    vagrant: True
    master: True

platforms:
  - name: debian-8.6

suites:
  - name: wordpress
