---
driver:
  name: vagrant
  # network:
  #   - ["forwarded_port", {guest: 80, host: 8000}

provisioner:
  name: salt_solo
  is_file_root: True
  grains:
    vagrant: true
  pillars-from-files:
    kitchen.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - kitchen
  state_top:
    base:
      '*':
        - system
        - services
        - web
platforms:
  - name: debian-8.6
  - name: ubuntu-14.04
  # - name: centos-7.2

suites:
  - name: default
