---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: salt_solo
  is_file_root: true
  state_top_from_file: true
  pillars-from-files:
    me.sls: test/pillars/me.sls
  pillars:
    top.sls:
      base:
        '*':
          - me
          - everything

platforms:
  - name: debian-8.6
  - name: ubuntu-14.04

suites:
  - name: columbia
    driver:
      customize:
        memory: 1024
      synced_folders:
        - ["./test/certs", "/etc/letsencrypt/live"]
    provisioner:
      pillars-from-files:
        everything.sls: test/pillars/columbia.sls
      grains:
        roles:
          - server
          - webserver

  - name: sriram
    driver:
      customize:
        memory: 512
      synced_folders:
        - ["./test/certs", "/etc/letsencrypt/live"]
    provisioner:
      pillars-from-files:
        everything.sls: test/pillars/sriram.sls
      grains:
        roles:
          - server
          - webserver
