language: ruby

env:
  global:
    - machine_user=travis
    - machine_pass=travis
    - machine_port=22
    - KITCHEN_LOCAL_YAML=.kitchen.travis.yml

rvm:
  - 2.1.7

sudo: required
dist: trusty
services: mysql

before_install:
  - sudo usermod -p "`openssl passwd -1 'travis'`" travis

script:
  - bundle exec kitchen test ubuntu

branches:
  only:
    - master

notifications:
  email: false
