language: python
python:
  - '2.7'

before_install:
  - curl -L https://bootstrap.saltstack.com | sudo sh -s -- stable

install:
  - sudo cp -r . /srv/salt/
  - sudo service salt-minion restart
  - sudo salt-call --local saltutil.sync_all
  - sudo salt-call --local grains.items

script:
  - sudo salt-call --local --retcode-passthrough --state-output=mixed test.ping

notifications:
  email: false
