language: python
python:
  - '2.7'

before_install:
  - sudo apt-get update
  - sudo service postgresql stop
  - sudo apt-get --purge remove postgresql\*
  - sudo apt-get install python-pip
  - sudo pip install docker-py
  - curl -L https://bootstrap.saltstack.com | sudo sh -s -- stable

install:
  - sudo cp -r . /srv/salt/
  - sudo cp -r ./test/travispillars /srv/pillar
  - sudo service salt-minion restart
  - sudo salt-call --local saltutil.sync_all
  - sudo salt-call --local grains.items

script:
  - sudo salt-call --local --retcode-passthrough state.sls system.locale
  - sudo salt-call --local --retcode-passthrough state.sls auth
  - sudo salt-call --local --retcode-passthrough state.sls services
  - sudo salt-call --local --retcode-passthrough state.sls web
  - python ./test/test.py

notifications:
  email: false
