language: ruby

env:
  global:
    - machine_user=travis
    - machine_pass=travis
    - machine_port=22
    - KITCHEN_LOCAL_YAML=.kitchen.travis.yml

rvm:
  - 2.1.7

sudo: required
dist: trusty

before_install:
  - sudo usermod -p "`openssl passwd -1 'travis'`" travis
  - sudo apt-get purge mysql-*
  - sudo apt-get autoremove
  - sudo apt-get autoclean
  - rm -rf /var/lib/mysql/debian-*

script:
  - bundle exec kitchen test ubuntu

branches:
  only:
    - master

notifications:
  email: false
