language: ruby

env:
  global:
    - machine_user=travis
    - machine_pass=travis
    - machine_port=22
    - KITCHEN_LOCAL_YAML=.kitchen.travis.yml
  matrix:
  - SUITE=nothing-ubuntu
  - SUITE=base-ubuntu
  - SUITE=webserver-ubuntu

rvm:
  - 2.1.7

sudo: required
dist: trusty

before_install:
  - sudo usermod -p "`openssl passwd -1 'travis'`" travis
  - sudo apt-get install python-pip
  - sudo pip install docker-py

script:
  - bundle exec kitchen test $SUITE

branches:
  only:
    - master

notifications:
  email: false
