language: python
python:
  - '2.7'

before_install:
  - sudo apt-get update
  - curl -L http://bootstrap.saltstack.org | sudo sh -s -- git develop

install:
  - sudo mkdir -p /srv/salt/
  - sudo mkdir -p /srv/pillar/
  - sudo cp -r . /srv/salt/
  - sudo cp ./travis/* /srv/pillar
  - sudo service salt-minion restart
  - sudo salt-call grains.items --local

script:
  - sudo salt-call --local --retcode-passthrough test.ping
