language: python
python:
  - '2.7'

before_install:
  - sudo apt-get update
  - sudo service postgresql stop
  - sudo apt-get --purge remove postgresql\*
  - curl -L https://bootstrap.saltstack.com | sudo sh -s -- stable

install:
  - sudo mkdir -p /srv/salt/
  - sudo mkdir -p /srv/pillar/
  - sudo cp -r . /srv/salt/
  - sudo cp ./travis/* /srv/pillar
  - sudo service salt-minion restart
  - sudo salt-call --local saltutil.sync_all
  - sudo salt-call grains.items --local

script:
  - sudo salt-call --local --retcode-passthrough state.sls system.locale
  - sudo salt-call --local --retcode-passthrough state.sls system.services
  - sudo salt-call --local --retcode-passthrough state.sls auth

notifications:
  email: false
