#!/usr/bin/env python
import urllib
import socket


def main():
    response = urllib.urlopen('http://backends.alexrecker.com/api/')
    content = ''.join(response.readlines())
    assert response.geturl() == 'http://backends.alexrecker.com'
    assert socket.gethostbyname('backends.alexrecker.com') == '127.0.0.1'
    exit()


if __name__ == '__main__':
    main()
