#!/usr/bin/env python
import urllib
import socket


def main():
    response = urllib.urlopen('http://backends.alexrecker.com/api/')
    content = ''.join(response.readlines())
    exit()


if __name__ == '__main__':
    main()
