#!/usr/bin/env python
import requests
import json


def main():
    response = requests.get('http://backends.alexrecker.com/api/')
    data = json.loads(response.content)

    assert response.status_code is 200

    for key in ['documents', 'images', 'fortune-cookies', 'images', 'subscribers']:
        assert data.has_key(key)

    exit()


if __name__ == '__main__':
    main()
