#!/usr/bin/env python
import urllib2

content = '''
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <title>Document</title>
  </head>
  <body>
    <h1>Test Page</h1>
  </body>
</html>
'''
target = '/var/www/blog-jekyll/index.html'

def main():
    with file(target, 'w+') as f:
        f.write(content)

    response = urllib2.urlopen('http://alexrecker.com')
    html = response.read()

    assert response.getcode() is 200, 'response code is actually {}'.format(response.getcode())

    assert 'Test Page' in html


if __name__ == '__main__':
    main()
