#!/usr/bin/env python
import urllib
import socket


def main():
    response = urllib.urlopen('http://bobrosssearch.com')
    content = ''.join(response.readlines())
    assert response.getcode() == 200
    assert response.geturl() == 'http://bobrosssearch.com'
    assert '<title>Bob Ross Search</title>' in content
    assert socket.gethostbyname('bobrosssearch.com') == '127.0.0.1'
    exit()


if __name__ == '__main__':
    main()
